import type { AdventureDefinition } from "../game/adventure";

export const initialAdventure = {
  places: [
    {
      id: "town-square",
      label: "街の広場",
      routes: [{ conversationId: "town-square" }],
    },
    {
      id: "guild",
      label: "冒険者ギルド",
      routes: [
        {
          conversationId: "guild-return-quest",
          when: { all: ["visited-guild", "heard-guild-quest"] },
        },
        {
          conversationId: "guild-return-unselected",
          when: { all: ["visited-guild"], none: ["heard-guild-quest"] },
        },
        { conversationId: "guild-first" },
      ],
    },
    {
      id: "market",
      label: "市場",
      routes: [{ conversationId: "market" }],
    },
    {
      id: "find-companion",
      label: "同行者を探す（仮）",
      routes: [
        { conversationId: "gilberta-already-joined", when: { all: ["joined-gilberta"] } },
        { conversationId: "gilberta-recruitment-sample" },
      ],
    },
  ],
  conversations: [
    {
      id: "gilberta-recruitment-sample",
      startNodeId: "meet",
      nodes: {
        meet: {
          type: "line",
          text: "ギルベルタに同行を相談する。（仮イベント）",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "neutral",
          position: "center",
          nextNodeId: "invite",
        },
        invite: {
          type: "choice",
          prompt: "ギルベルタを仲間に迎える？（仮イベント）",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "neutral",
          position: "center",
          options: [
            { id: "invite-gilberta", label: "仲間に迎える", nextNodeId: "join" },
            { id: "leave", label: "今は見送る", nextNodeId: "end" },
          ],
        },
        join: {
          type: "end",
          recruitments: [
            { characterId: "gilberta", when: { none: ["joined-gilberta"] }, setFlags: ["joined-gilberta"] },
          ],
        },
        end: { type: "end" },
      },
    },
    {
      id: "gilberta-already-joined",
      startNodeId: "joined",
      nodes: {
        joined: {
          type: "line",
          text: "ギルベルタは加入済みです。（仮イベント）",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "neutral",
          position: "center",
          nextNodeId: "end",
        },
        end: { type: "end" },
      },
    },
    {
      id: "town-square",
      startNodeId: "look-around",
      nodes: {
        "look-around": {
          type: "line",
          text: "ここは街の広場。まずはどこへ行こう？",
          speakerName: "ロッシ",
          backgroundId: "town-square",
          portraitId: "rossi",
          expressionId: "smile",
          position: "center",
          nextNodeId: "end",
        },
        end: { type: "end" },
      },
    },
    {
      id: "guild-first",
      startNodeId: "approach-guild",
      onCompleteFlags: ["visited-guild"],
      nodes: {
        "approach-guild": {
          type: "line",
          text: "ロッシは掲示板の前で足を止めた。",
          speakerName: "ロッシ",
          backgroundId: "guild-hall",
          portraitId: "rossi",
          expressionId: "neutral",
          position: "left",
          nextNodeId: "greeting",
        },
        greeting: {
          type: "line",
          text: "ギルベルタが掲示板の前で会釈した。",
          speakerName: "ギルベルタ",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "smile",
          position: "center",
          nextNodeId: "ask-about-work",
        },
        "ask-about-work": {
          type: "choice",
          prompt: "何を聞こう？",
          speakerName: "ギルベルタ",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "smile",
          position: "center",
          options: [
            {
              id: "ask-quest",
              label: "掲示板の依頼について聞く",
              nextNodeId: "quest-answer",
              setFlags: ["heard-guild-quest"],
            },
            {
              id: "ask-secret",
              label: "極秘依頼について聞く",
              nextNodeId: "secret-answer",
              when: { all: ["knows-secret"] },
            },
            {
              id: "leave",
              label: "今日は何も聞かない",
              nextNodeId: "end",
            },
          ],
        },
        "quest-answer": {
          type: "line",
          text: "街道の様子を調べる依頼が出ているそうだ。",
          speakerName: "ギルベルタ",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "neutral",
          position: "center",
          nextNodeId: "end",
        },
        "secret-answer": {
          type: "line",
          text: "ギルベルタは声をひそめ、奥の部屋を指した。",
          speakerName: "ギルベルタ",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "serious",
          position: "center",
          nextNodeId: "end",
        },
        end: { type: "end" },
      },
    },
    {
      id: "guild-return-quest",
      startNodeId: "follow-up-quest",
      onCompleteFlags: ["visited-guild"],
      nodes: {
        "follow-up-quest": {
          type: "line",
          text: "ギルベルタは前回の話を覚えていた。「街道調査の依頼、詳しい内容をまとめておきました」",
          speakerName: "ギルベルタ",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "smile",
          position: "center",
          nextNodeId: "end",
        },
        end: { type: "end" },
      },
    },
    {
      id: "guild-return-unselected",
      startNodeId: "welcome-back-unselected",
      onCompleteFlags: ["visited-guild"],
      nodes: {
        "welcome-back-unselected": {
          type: "line",
          text: "ギルベルタは顔を覚えていた。「前回は依頼の話をしませんでしたね。今日は何か聞きますか？」",
          speakerName: "ギルベルタ",
          backgroundId: "guild-hall",
          portraitId: "gilberta",
          expressionId: "smile",
          position: "center",
          nextNodeId: "end",
        },
        end: { type: "end" },
      },
    },
    {
      id: "market",
      startNodeId: "market-greeting",
      nodes: {
        "market-greeting": {
          type: "line",
          text: "市場には旅支度をする人たちが集まっている。必要な物を見て回ろう。",
          speakerName: "ロッシ",
          backgroundId: "town-market",
          portraitId: "rossi",
          expressionId: "smile",
          position: "right",
          nextNodeId: "end",
        },
        end: { type: "end" },
      },
    },
    {
      id: "dungeon-scouting",
      startNodeId: "find-tracks",
      onCompleteFlags: ["scouted-ruins"],
      nodes: {
        "find-tracks": {
          type: "line",
          text: "道の脇に、遺跡へ続く新しい足跡が残っている。",
          speakerName: "ロッシ",
          backgroundId: "roadside",
          portraitId: "rossi",
          expressionId: "serious",
          position: "left",
          nextNodeId: "choose-route-marking",
        },
        "choose-route-marking": {
          type: "choice",
          prompt: "足跡を記録する？",
          speakerName: "ロッシ",
          backgroundId: "roadside",
          portraitId: "rossi",
          expressionId: "neutral",
          position: "left",
          options: [
            {
              id: "mark-on-map",
              label: "地図に足跡を記す",
              nextNodeId: "end",
              setFlags: ["marked-ruins-route"],
            },
            {
              id: "continue-without-marking",
              label: "記録せずに先へ進む",
              nextNodeId: "end",
            },
          ],
        },
        end: { type: "end" },
      },
    },
  ],
} as const satisfies AdventureDefinition;
