import type { SkillCatalog } from "../game/skills";

/** All names, effect amounts and fatigue increases are provisional test data. */
export const skillCatalog = {
  skills: [
    {
      id: "test-strike",
      name: "検証用攻撃",
      description: "生存中の敵1体へ12ダメージ。",
      tier: "normal",
      type: "active",
      effect: { type: "damage", amount: 12 },
      mentalFatigueIncrease: 4,
      scenes: ["battle"],
      target: "single-enemy",
    },
    {
      id: "test-heal",
      name: "検証用回復",
      description: "生存中の味方1体のHPを8回復。自分も対象。",
      tier: "normal",
      type: "active",
      effect: { type: "hp-recovery", amount: 8 },
      mentalFatigueIncrease: 3,
      scenes: ["battle", "branch"],
      target: "single-ally",
    },
    {
      id: "test-strength",
      name: "検証用攻撃力補正",
      description: "習得中、自分の通常攻撃力に2を加算。",
      tier: "normal",
      type: "passive",
      effect: { type: "basic-attack-power-bonus", amount: 2 },
    },
    {
      id: "test-strike-advanced",
      name: "検証用上位攻撃",
      description: "生存中の敵1体へ24ダメージ。",
      tier: "advanced",
      type: "active",
      effect: { type: "damage", amount: 24 },
      mentalFatigueIncrease: 8,
      scenes: ["battle"],
      target: "single-enemy",
    },
    {
      id: "test-heal-advanced",
      name: "検証用上位回復",
      description: "生存中の味方1体のHPを16回復。自分も対象。",
      tier: "advanced",
      type: "active",
      effect: { type: "hp-recovery", amount: 16 },
      mentalFatigueIncrease: 6,
      scenes: ["battle", "branch"],
      target: "single-ally",
    },
    {
      id: "test-strength-advanced",
      name: "検証用上位攻撃力補正",
      description: "習得中、自分の通常攻撃力に4を加算。",
      tier: "advanced",
      type: "passive",
      effect: { type: "basic-attack-power-bonus", amount: 4 },
    },
    {
      id: "test-strike-ultimate",
      name: "検証用最上位攻撃",
      description: "生存中の敵1体へ36ダメージ。",
      tier: "ultimate",
      type: "active",
      effect: { type: "damage", amount: 36 },
      mentalFatigueIncrease: 12,
      scenes: ["battle"],
      target: "single-enemy",
    },
    {
      id: "test-heal-ultimate",
      name: "検証用最上位回復",
      description: "生存中の味方1体のHPを24回復。自分も対象。",
      tier: "ultimate",
      type: "active",
      effect: { type: "hp-recovery", amount: 24 },
      mentalFatigueIncrease: 9,
      scenes: ["battle", "branch"],
      target: "single-ally",
    },
    {
      id: "test-strength-ultimate",
      name: "検証用最上位攻撃力補正",
      description: "習得中、自分の通常攻撃力に6を加算。",
      tier: "ultimate",
      type: "passive",
      effect: { type: "basic-attack-power-bonus", amount: 6 },
    },
  ],
  pools: [
    {
      id: "test-shared",
      candidates: {
        normal: ["test-strike", "test-heal", "test-strength"],
        advanced: ["test-strike-advanced", "test-heal-advanced", "test-strength-advanced"],
        ultimate: ["test-strike-ultimate", "test-heal-ultimate", "test-strength-ultimate"],
      },
    },
  ],
  characters: [
    { characterId: "player", poolId: "test-shared", initialSkillIds: null },
    { characterId: "gilberta", poolId: "test-shared", initialSkillIds: null },
  ],
} as const satisfies SkillCatalog;
