import type { SkillCatalog } from "../game/skills";

/** Initial loadouts are trial skills, not the characters' canonical signature moves.
 * All names, scaling, rank caps/effects and fatigue increases are provisional test data. */
export const skillCatalog = {
  skills: [
    {
      id: "test-strike",
      name: "検証用攻撃",
      description: "生存中の敵1体へ、12＋攻撃力×0.5のダメージ。",
      tier: "normal",
      type: "active",
      effect: { type: "damage", amount: 12, scaling: { stat: "attackPower", coefficient: 0.5 } },
      mentalFatigueIncrease: 4,
      scenes: ["battle"],
      target: "single-enemy",
    },
    {
      id: "test-heal",
      name: "検証用回復",
      description: "生存中の味方1体のHPを8＋最大HP×0.5回復。自分も対象。",
      tier: "normal",
      type: "active",
      effect: { type: "hp-recovery", amount: 8, scaling: { stat: "maxHp", coefficient: 0.5 } },
      mentalFatigueIncrease: 3,
      scenes: ["battle", "branch"],
      target: "single-ally",
    },
    {
      id: "test-strength",
      name: "検証用攻撃力補正",
      description: "習得中、自分の通常攻撃力にランク1で2、ランク2で4を加算。",
      tier: "normal",
      type: "passive",
      effect: { type: "basic-attack-power-bonus", rankAmounts: [2, 4] },
    },
    {
      id: "test-power",
      name: "検証用威力補正",
      description: "攻撃力に2／3／5を加算。攻撃スキルにも反映。",
      tier: "normal",
      type: "passive",
      effect: { type: "attack-power-bonus", rankAmounts: [2, 3, 5] },
    },
    {
      id: "test-vitality",
      name: "検証用体力補正",
      description: "最大HPに4／7を加算。回復スキルにも反映。",
      tier: "normal",
      type: "passive",
      effect: { type: "max-hp-bonus", rankAmounts: [4, 7] },
    },
    {
      id: "test-light-strike",
      name: "検証用軽撃",
      description: "攻撃力×1.5のダメージ。精神疲労増加なし。",
      tier: "normal",
      type: "active",
      effect: { type: "damage", amount: 0, scaling: { stat: "attackPower", coefficient: 1.5 } },
      mentalFatigueIncrease: 0,
      scenes: ["battle"],
      target: "single-enemy",
    },
    {
      id: "test-mend",
      name: "検証用応急回復",
      description: "生存味方1体のHPを2＋最大HP×0.3回復。",
      tier: "normal",
      type: "active",
      effect: { type: "hp-recovery", amount: 2, scaling: { stat: "maxHp", coefficient: 0.3 } },
      mentalFatigueIncrease: 1,
      scenes: ["battle", "branch"],
      target: "single-ally",
    },
    {
      id: "test-strike-advanced",
      name: "検証用上位攻撃",
      description: "生存中の敵1体へ、24＋攻撃力×0.5のダメージ。",
      tier: "advanced",
      type: "active",
      effect: { type: "damage", amount: 24, scaling: { stat: "attackPower", coefficient: 0.5 } },
      mentalFatigueIncrease: 8,
      scenes: ["battle"],
      target: "single-enemy",
    },
    {
      id: "test-heal-advanced",
      name: "検証用上位回復",
      description: "生存中の味方1体のHPを16＋最大HP×0.5回復。自分も対象。",
      tier: "advanced",
      type: "active",
      effect: { type: "hp-recovery", amount: 16, scaling: { stat: "maxHp", coefficient: 0.5 } },
      mentalFatigueIncrease: 6,
      scenes: ["battle", "branch"],
      target: "single-ally",
    },
    {
      id: "test-strength-advanced",
      name: "検証用上位攻撃力補正",
      description: "習得中、自分の通常攻撃力にランク1で4、ランク2で8を加算。",
      tier: "advanced",
      type: "passive",
      effect: { type: "basic-attack-power-bonus", rankAmounts: [4, 8] },
    },
    {
      id: "test-strike-ultimate",
      name: "検証用最上位攻撃",
      description: "生存中の敵1体へ、36＋攻撃力×0.5のダメージ。",
      tier: "ultimate",
      type: "active",
      effect: { type: "damage", amount: 36, scaling: { stat: "attackPower", coefficient: 0.5 } },
      mentalFatigueIncrease: 12,
      scenes: ["battle"],
      target: "single-enemy",
    },
    {
      id: "test-heal-ultimate",
      name: "検証用最上位回復",
      description: "生存中の味方1体のHPを24＋最大HP×0.5回復。自分も対象。",
      tier: "ultimate",
      type: "active",
      effect: { type: "hp-recovery", amount: 24, scaling: { stat: "maxHp", coefficient: 0.5 } },
      mentalFatigueIncrease: 9,
      scenes: ["battle", "branch"],
      target: "single-ally",
    },
    {
      id: "test-strength-ultimate",
      name: "検証用最上位攻撃力補正",
      description: "習得中、自分の通常攻撃力にランク1で6、ランク2で12を加算。",
      tier: "ultimate",
      type: "passive",
      effect: { type: "basic-attack-power-bonus", rankAmounts: [6, 12] },
    },
  ],
  pools: [
    {
      id: "test-shared",
      candidates: {
        normal: [
          "test-strike",
          "test-heal",
          "test-strength",
          "test-power",
          "test-vitality",
          "test-light-strike",
          "test-mend",
        ],
        advanced: ["test-strike-advanced", "test-heal-advanced", "test-strength-advanced"],
        ultimate: ["test-strike-ultimate", "test-heal-ultimate", "test-strength-ultimate"],
      },
    },
  ],
  characters: [
    { characterId: "player", poolId: "test-shared", initialSkillIds: ["test-strike", "test-heal"] },
    { characterId: "gilberta", poolId: "test-shared", initialSkillIds: ["test-strike", "test-heal"] },
  ],
} as const satisfies SkillCatalog;
